### ISSUE TITLE
Movies and tvshows not showing

### ISSUE THREAD

**Issue by ChassterTP** [dindoquitor/juanfiTheme#2]
Nag redirect sa ibang sites, hindi po makanood

**Comment by dindoquitor** [comment]
Good day po, Yan talaga po ang resulta ng free lang na server ng video for streaming. Mya ads par kumita ang owner ng server at may pambayad sila sa cost ng pag run ng server...Pero sa akin kasi pinapagamit ko mga client ko ng Brave or firefox focus na browser pag gusto nila manood ng movies...

**Comment by ChassterTP** [comment]
Ah sakin din po brave, pero sa chrome di maganda.. salamat po sa portal😅
